# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteboard', '0002_auto_20151205_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noteboard.City'),
        ),
    ]
