# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteboard', '0002_auto_20151220_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
